# =============================================================================
# IAM Roles for Databricks Lakehouse Federation
#
# IMPORTANT: Following the official Terraform pattern, the order is:
#   1. Create Databricks credentials (with constructed IAM role ARN)
#   2. Databricks auto-generates the external_id
#   3. Use databricks_aws_unity_catalog_assume_role_policy data source
#      to generate the correct trust policy (with external_id + self-assume)
#   4. Create IAM roles with the generated trust policy
#
# This avoids the chicken-and-egg problem and eliminates manual ID lookup.
#
# See: https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/unity-catalog
# =============================================================================

data "aws_caller_identity" "current" {}

locals {
  aws_account_id = data.aws_caller_identity.current.account_id

  # Pre-compute role names (used to construct ARNs before roles exist)
  glue_role_name    = "${var.project_prefix}-databricks-glue"
  storage_role_name = "${var.project_prefix}-databricks-storage"

  # Glue database name (underscores for SQL compatibility)
  glue_database_name = replace("${var.project_prefix}_factory_master", "-", "_")
}

# =============================================================================
# Role 1: Glue API Access (for Databricks Service Credential)
# =============================================================================

# Trust policy generated by Databricks data source (includes master role ARN,
# external_id from credential, and self-assume statement)
data "databricks_aws_unity_catalog_assume_role_policy" "glue" {
  aws_account_id = local.aws_account_id
  role_name      = local.glue_role_name
  external_id    = databricks_credential.glue_service.aws_iam_role[0].external_id
}

resource "aws_iam_role" "databricks_glue" {
  name               = local.glue_role_name
  assume_role_policy = data.databricks_aws_unity_catalog_assume_role_policy.glue.json
}

resource "aws_iam_role_policy" "glue_access" {
  name = "${var.project_prefix}-glue-access"
  role = aws_iam_role.databricks_glue.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "GlueReadAccess"
        Effect = "Allow"
        Action = [
          "glue:GetDatabase",
          "glue:GetDatabases",
          "glue:GetTable",
          "glue:GetTables",
          "glue:GetTableVersion",
          "glue:GetTableVersions",
          "glue:GetPartition",
          "glue:GetPartitions",
          "glue:BatchGetPartition",
          "glue:GetUserDefinedFunction",
          "glue:GetUserDefinedFunctions",
        ]
        Resource = [
          "arn:aws:glue:${var.aws_region}:${local.aws_account_id}:catalog",
          "arn:aws:glue:${var.aws_region}:${local.aws_account_id}:catalog*",
          "arn:aws:glue:${var.aws_region}:${local.aws_account_id}:database/${local.glue_database_name}",
          "arn:aws:glue:${var.aws_region}:${local.aws_account_id}:table/${local.glue_database_name}/*",
        ]
      },
      {
        Sid      = "SelfAssumeRole"
        Effect   = "Allow"
        Action   = ["sts:AssumeRole"]
        Resource = ["arn:aws:iam::${local.aws_account_id}:role/${local.glue_role_name}"]
      }
    ]
  })
}

# =============================================================================
# Role 2: S3 Data Access (for Databricks Storage Credential)
# =============================================================================

# Trust policy generated by Databricks data source
data "databricks_aws_unity_catalog_assume_role_policy" "storage" {
  aws_account_id = local.aws_account_id
  role_name      = local.storage_role_name
  external_id    = databricks_storage_credential.glue_storage.aws_iam_role[0].external_id
}

resource "aws_iam_role" "databricks_storage" {
  name               = local.storage_role_name
  assume_role_policy = data.databricks_aws_unity_catalog_assume_role_policy.storage.json
}

resource "aws_iam_role_policy" "s3_read_access" {
  name = "${var.project_prefix}-s3-read"
  role = aws_iam_role.databricks_storage.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "S3ReadAccess"
        Effect = "Allow"
        Action = [
          "s3:GetObject",
          "s3:GetObjectVersion",
          "s3:ListBucket",
          "s3:GetBucketLocation",
        ]
        Resource = [
          aws_s3_bucket.glue_data.arn,
          "${aws_s3_bucket.glue_data.arn}/*",
        ]
      },
      {
        Sid      = "SelfAssumeRole"
        Effect   = "Allow"
        Action   = ["sts:AssumeRole"]
        Resource = ["arn:aws:iam::${local.aws_account_id}:role/${local.storage_role_name}"]
      }
    ]
  })
}
