# =============================================================================
# General
# =============================================================================

variable "project_prefix" {
  description = "Prefix for all resource names"
  type        = string
  default     = "lhf-demo"
}

# =============================================================================
# AWS
# =============================================================================

variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-west-2"
}

# NOTE: aws_account_id is obtained automatically via data.aws_caller_identity

# =============================================================================
# Databricks
# =============================================================================

variable "databricks_host" {
  description = "Databricks workspace URL (e.g. https://e2-demo-field-eng.cloud.databricks.com)"
  type        = string
}

variable "databricks_token" {
  description = "Databricks personal access token"
  type        = string
  sensitive   = true
}

# NOTE: External ID for IAM trust policy is auto-generated by Databricks
#       when credentials are created. No manual input needed.

# =============================================================================
# Redshift
# =============================================================================

variable "redshift_admin_password" {
  description = "Redshift Serverless admin password (min 8 chars, must include uppercase, lowercase, and number)"
  type        = string
  sensitive   = true
}
